broker:
  host: "localhost"
  port: 1883
  client_id: "magistrate_client_8"

client_magistrate:
  input_topic: "pipeline_inference_8"

  key_area_settings:
    alpha: 0.2
    area:
      - - 0
        - 0
      - - 300
        - 0
      - - 300
        - 300
      - - 0
        - 300
    color: '#FF0000'
    real_width:  300  # centimeters
    real_height: 300  # centimeters

  key_area_strategy:

    look_around:
      enable: true
      threshold: 3              # when the event exceeds or reaches the number of times
      penalty_score: 5          # penalty score X times

    theft_detection:
      enable: true
      threshold: 1              # when the event exceeds or reaches the number of times
      penalty_score: 30         # penalty score X times

    long_time_squat:
      enable: true
      threshold: 3              # when the event exceeds or reaches the seconds
      penalty_score: 5          # penalty score X duration
    
    loitering_distance:
      enable: true
      threshold: 500            # when the event exceeds or reaches the centimeters
      penalty_score: 5          # penalty score X distance

    loitering_reentry:
      enable: true
      threshold: 3              # when the event exceeds or reaches the number of times
      penalty_score: 5          # penalty score X times

    loitering_enter_area:
      enable: true
      threshold: 3              # when the event exceeds or reaches the number of times
      penalty_score: 5          # penalty score X times

  
  normal_area_strategy:

    look_around:
      enable: true
      threshold: 3              # when the event exceeds or reaches the number of times
      penalty_score: 5          # penalty score X times

    theft_detection:
      enable: true
      threshold: 1              # when the event exceeds or reaches the number of times
      penalty_score: 30         # penalty score X times

    long_time_squat:
      enable: true
      threshold: 3              # when the event exceeds or reaches the seconds
      penalty_score: 5          # penalty score X duration
    
    loitering_distance:
      enable: true
      threshold: 500            # when the event exceeds or reaches the centimeters
      penalty_score: 5          # penalty score X distance

    loitering_reentry:
      enable: true
      threshold: 3              # when the event exceeds or reaches the number of times
      penalty_score: 5          # penalty score X times

    loitering_enter_area:
      enable: true
      threshold: 3              # when the event exceeds or reaches the number of times
      penalty_score: 5          # penalty score X times

  alert_settings:
    level0: 0   # gray
    level1: 5   # green
    level2: 10  # cyan
    level3: 15  # yellow
    level4: 20  # orange
    level5: 25  # red

  cloud:
    enable: true
    blocking_duration: 300      # seconds
    upload_level: 2

    sceptical_image:
      script: "/opt/SurveillanceService/scripts/cloud/upload_sceptical_image_to_cloud.sh"
      device_id: "0000000055"
      action_code: "998"

    patrol_image:
      script: "/opt/SurveillanceService/scripts/cloud/upload_confirmation_image_to_cloud.sh"
      device_id: "0000000055"
      action_code: "001"


general_settings:
  schema_config: ./configs/scheme.json
  use_enhanced_tracking: false
  enable_debug_mode: false
  display_width: 1024
  display_height: 768
  sma_window_size: 15
  delta_duration_threshold: 1.0
  delta_distance_threshold: 3.0
  reentry_angle_threshold: 45.0
  min_consecutive_count: 2
  min_keypoint_distance: 20.0
  cache_retention_duration: 60